# Generated by Django 2.1 on 2019-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=25)),
                ('messege', models.TextField(null=True)),
            ],
        ),
    ]
